### ISSUE TITLE
Add Extension:GuidedTour 

### ISSUE THREAD

**Issue by kelson42** [kiwix/wikifundi#14]
Add the guide tour extension to the Media Wiki set up. 
See https://www.mediawiki.org/wiki/Extension:GuidedTour

**Comment by kelson42** [comment]
@florentk If you can confirm/infirm that this function/extension is going to work that would be helpful. Florence is currently working on the redactional part of the project here https://fr.wikipedia.org/wiki/Projet:WikiFundi/Tutoriels and would like confirmation before investigating more energy with this Mediawiki feature.

**Comment by florentk** [comment]
I added and tested this extension in Docker image, it's ok for me

**Comment by kelson42** [comment]
@florentk Thank you for checking this. I will close the issue if this is integrated.
@Anthere You can go ahead with your documents using Extension:GuidedTour

**Comment by Anthere** [comment]
Ok ! Good to know !

Flo

Le 16/05/2018 à 18:12, Kelson a écrit :
