### ISSUE TITLE
use exclusively Composer to install MW extension

### ISSUE THREAD

**Issue by florentk** [kiwix/wikifundi#18]
MediaWiki has many way to install extension : tarball, git, Composer (script PHP) *. Check if we can use exclusively Composer for all used extension
* https://www.mediawiki.org/wiki/Composer/For_extensions

**Comment by kelson42** [comment]
@florentk What is the status on that?

**Comment by florentk** [comment]
It's always open

**Comment by florentk** [comment]
moved to https://github.com/openzim/mediawiki-docker/issues/5
