### ISSUE TITLE
Map do not display in city Infobox 

### ISSUE THREAD

**Issue by florentk** [kiwix/wikifundi#19]
Problem to generate thumbnail with some SVG file ("Invalid SVG file: Expected <svg> tag, got in NS")

**Comment by kelson42** [comment]
@florentk check that SVG are generated with rsvg

**Comment by florentk** [comment]
@kelson42 yes, I have in LocalSetting.php :
`$wgSVGConverters = array( 'rsvg' => '/usr/bin/rsvg-convert -w $width -h $height -o $output $input');
$wgSVGConverter = 'rsvg' ;`

**Comment by florentk** [comment]
@kelson42 rsvg is currently used, it work for any other SVG file. When I analyse logs, MW call the script to generate thumbnail for any other SVG file, but not for map SVG in Infobox. I not get error to. I don't understand.

**Comment by kelson42** [comment]
@florentk Do you have a concrete example?

**Comment by florentk** [comment]
fixed with nginx version !?
