### ISSUE TITLE
Display issue on macintosh

### ISSUE THREAD

**Issue by Anthere** [kiwix/wikifundi#2]
The window in which WikiFundi opens on an Apple computer is fixed and does not present the regular features of a browser.

**Comment by kelson42** [comment]
This is a feature from macos. I have tried to find a way to deactivate it, but I did not have found any easy way.

**Comment by kelson42** [comment]
Myself and @rgaudin have tested this newly with new Kiwix-plug solution (Ideascube) and problem seems to be fixed. We are not prisonner anymore from the small dialog browser on macOS.
