### ISSUE TITLE
File Uploads limited to 2MiB

### ISSUE THREAD

**Issue by rgaudin** [kiwix/wikifundi#25]
By default, `php-fpm` has an upload size limit of `2MiB` which seems too short for Wikifundi.

I can't try and run the image creation but looking at the Dockerfile, you did not change this value (`ini_set` in `LocalSettings.php` should not work by default neither).

You could simply fix this by adding an `/etc/php/7.0/fpm/conf.d/90-wikifundi.ini` file:

``` ini
upload_max_filesize = 100M
post_max_size = 100M
```

**Comment by florentk** [comment]
I had add this to limit at 100M. This is in the yesterday version 
`RUN { \
		echo 'upload_max_filesize = 100M'; \
		echo 'post_max_size = 100M'; \
	} > /usr/local/etc/php/conf.d/90-wikifundi.ini`

**Comment by kelson42** [comment]
@florentk Thx, could you fix please the php conf file in `openzim/mediawiki` (not sure myself where it should be) and provide a similar code in `kiwix/wikifundi` but to **10MB** (lowend devices like RPI can not resize properly bigger files due to the lack of memory).

**Comment by rgaudin** [comment]
Unfortunately, there is no finer option to allow files with no thumbnail up to a larger size than images.
On a Pi2, a 9MB image could not be resized even with a 3mn timeout.

**Comment by kelson42** [comment]
@rgaudin Thank you for the feedback, so I vote for a limit at 5MB.

**Comment by florentk** [comment]
@kelson42 i'am set max file size to 5MB, but I have not right to push on openzim/mediawiki

**Comment by kelson42** [comment]
@florentk You should have got and invitation, I have invited you at the time I have open the repo this morning. Feel free to come on IRC #kiwix to discuss the details.

**Comment by florentk** [comment]
@kelson42 sorry It's ok now

**Comment by kelson42** [comment]
@florentk You PR seems wrong, set 100MB for `openzim/mediawiki` and 5MB for `kiwix/wikifundi`.

**Comment by florentk** [comment]
ok ok, it's logic :) the last PRs must be ok

**Comment by kelson42** [comment]
@florentk Thx, looks good (if it works, I do not have tested).
