### ISSUE TITLE
Split developer README and user README

### ISSUE THREAD

**Issue by kelson42** [kiwix/wikifundi#28]
We face here two types of users:
* The DEV one wanting to rebuild the Wikifundi from scratch
* The FINAL one wanting to use the final Docker or data dump

Each of them need a README:
* The DEV one should keep the git repo root README.md
* The FINAL one should gets it's README with the data dump and I think the container shuld (re-)write it each time it (re-)start to the data volume

**Comment by florentk** [comment]
added in a7e9f82
