### ISSUE TITLE
Non access to digital resources on an apple computer

### ISSUE THREAD

**Issue by Anthere** [kiwix/wikifundi#3]
It is not possible to access the digital resources (pdf, videos, images, mooc content ) when on an Apple computer. The links and categories appear, but clicking on them does not make any difference. No loading. 

The digital resources do display on an iphone though.

**Comment by kelson42** [comment]
This is a feature from macos. I have tried to find a way to deactivate it, but I did not have found any easy way. Basically macos detects that this is a captive portal and does a few things on its own... For example launching a primitive web browser... and I see no way on the server side to avoid this.

**Comment by Anthere** [comment]
So it means that for next version, it is probably wiser to remove that section entirely and only keep resources on the wiki. I think it is too confusing for all mac users to try to access resources and get nothing working. That looks bad.

**Comment by kelson42** [comment]
This should be fixed now, as we are not prisoner anymore from the captive portal limited browser.
